import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { BrowserWindow, app, ipcMain, nativeTheme, session } from 'electron';
import { EVENT_CHANNELS, type AppInfo, type UpdateState } from '../shared/types/ipc.js';
import { resolvePlatform } from '../shared/platform.js';
import { registerWindowIpc } from './ipc/register-window-ipc.js';
import { registerTabIpc } from './ipc/register-tab-ipc.js';
import { registerSettingsIpc } from './ipc/register-settings-ipc.js';
import type { IpcContractError } from './ipc/contract-guard.js';
import { popupTabMenu } from './menus/tab-menu.js';
import { loadBlocker, type BlockerHandle } from './privacy/adblock.js';
import { buildUserAgent, UPDATE_FEED_URL, type BrowserIdentity } from './privacy/policies.js';
import { clearBrowsingData } from './privacy/session-hardening.js';
import { SettingsStore } from './settings/store.js';
import { normalizeUrl } from '../shared/url.js';
import { defaultTileTitle } from './speed-dial.js';
import { Updater } from './updates/updater.js';
import { FaviconCache } from './favicons/favicon-cache.js';
import { HistoryStore } from './history/history-store.js';
import { Vault } from './account/vault.js';
import { LocalModel } from './assistant/local-model.js';
import { ModelStore } from './assistant/model-store.js';
import { findModel, MODEL_CATALOGUE } from './assistant/catalogue.js';
import { fillLogin } from './account/autofill.js';
import { startDevMetrics } from './dev-metrics.js';
import { SURFACE } from './window-options.js';
import { VelaWindow } from './vela-window.js';

const PLATFORM = resolvePlatform(process.platform);
const IS_DEV = !app.isPackaged;

/** Build output root. Resolves identically in dev and inside the packaged asar. */
const APP_PATH = app.getAppPath();
const OUT_DIR = path.join(APP_PATH, 'out');
const PRELOAD_PATH = path.join(OUT_DIR, 'preload', 'index.cjs');
const RENDERER_HTML = path.join(OUT_DIR, 'renderer', 'index.html');
/**
 * Where the shipped ad/tracker engine lives. In a packaged build `extraResources`
 * land beside the asar, not inside it, so this is `process.resourcesPath` there
 * and the repo's own `resources/` directory in development.
 */
const RESOURCES_DIR = app.isPackaged ? process.resourcesPath : path.join(APP_PATH, 'resources');
const DEV_SERVER_URL = process.env['VELA_DEV_SERVER_URL'];
/** Generated by scripts/make-icon.mjs and shipped in the build resources. */
const ICON_PATH = path.join(APP_PATH, 'build', 'icon.png');

/** One identity, built once, for both the UA string and the client hints. */
const BROWSER_IDENTITY: BrowserIdentity = {
  platform: PLATFORM,
  chromeMajorVersion: process.versions.chrome.split('.')[0] ?? '140',
};
const USER_AGENT = buildUserAgent(BROWSER_IDENTITY.platform, BROWSER_IDENTITY.chromeMajorVersion);

app.setName('Vela');

// Lets the E2E suite run against a throwaway profile instead of the real one.
// Nothing reads this in a packaged build unless the user sets it themselves.
const USER_DATA_OVERRIDE = process.env['VELA_USER_DATA_DIR'];
if (USER_DATA_OVERRIDE !== undefined && USER_DATA_OVERRIDE !== '') {
  app.setPath('userData', USER_DATA_OVERRIDE);
}

const windows = new Map<number, VelaWindow>();
let settings: SettingsStore | null = null;
let blocker: BlockerHandle | null = null;
let favicons: FaviconCache | null = null;
let updater: Updater | null = null;
let history: HistoryStore | null = null;
let vault: Vault | null = null;

/**
 * The assistant's model: the file on disk, and llama.cpp holding it open.
 *
 * Both live for the life of the app rather than per window — a model is
 * hundreds of megabytes resident, and two windows asking questions should be
 * asking the same loaded copy.
 */
const localModel = new LocalModel();
let modelStore: ModelStore | null = null;

function broadcastModelProgress(payload: unknown): void {
  for (const window of windows.values()) {
    window.send(EVENT_CHANNELS.assistantModelProgress, payload);
  }
}

function getAppInfo(): AppInfo {
  return {
    name: 'Vela',
    version: app.getVersion(),
    electronVersion: process.versions.electron,
    chromeVersion: process.versions.chrome,
    platform: PLATFORM,
    isDev: IS_DEV,
  };
}

function backgroundColor(): string {
  const preference = settings?.current.theme ?? 'system';
  const dark = preference === 'system' ? nativeTheme.shouldUseDarkColors : preference === 'dark';
  return dark ? SURFACE.dark : SURFACE.light;
}

/** Resolves which window an IPC message came from. */
function windowFor(sender: unknown): VelaWindow | null {
  for (const window of windows.values()) {
    if (window.owns(sender)) return window;
  }
  return null;
}

function onUnexpectedRequest(url: string): void {
  // Vela makes exactly two kinds of request: pages the user navigated to and
  // the update check. Anything else is a bug, caught here in development
  // rather than after shipping.
  console.error(`[privacy] unexpected request from Vela itself: ${url}`);
}

function createWindow(options: { isPrivate: boolean }): VelaWindow {
  if (settings === null) throw new Error('settings store is not ready');

  const window = new VelaWindow({
    platform: PLATFORM,
    preloadPath: PRELOAD_PATH,
    rendererHtml: RENDERER_HTML,
    devServerUrl: DEV_SERVER_URL,
    backgroundColor: backgroundColor(),
    iconPath: ICON_PATH,
    userAgent: USER_AGENT,
    identity: BROWSER_IDENTITY,
    isDev: IS_DEV,
    isPrivate: options.isPrivate,
    settings,
    blocker,
    favicons,
    history,
    vault,
    onClosed: (closed) => windows.delete(closed.id),
    onUnexpectedRequest,
  });

  windows.set(window.id, window);
  return window;
}

/** Pushes update state to every open window. */
function broadcastUpdateState(state: UpdateState): void {
  for (const window of windows.values()) {
    window.send(EVENT_CHANNELS.updateStateChanged, state);
  }
}

function onIpcViolation(error: IpcContractError): void {
  console.error(error.message);
}

/** Honours the clear-on-exit toggle before the app goes away. */
async function clearOnExitIfRequested(): Promise<void> {
  if (settings?.current.clearOnExit !== true) return;
  await clearBrowsingData(session.defaultSession);
}

if (!app.requestSingleInstanceLock()) {
  app.quit();
} else {
  app.on('second-instance', () => {
    const [first] = windows.values();
    if (first === undefined) return;
    if (first.window.isMinimized()) first.window.restore();
    first.window.focus();
  });

  void app.whenReady().then(async () => {
    settings = new SettingsStore();
    updater = new Updater({
      isEnabled: () => settings?.current.checkForUpdates ?? false,
      onStateChanged: (state) => {
        broadcastUpdateState(state);
      },
    });

    modelStore = new ModelStore(path.join(app.getPath('userData'), 'models'), (progress) => {
      broadcastModelProgress(progress);
    });

    history = new HistoryStore();
    vault = new Vault();
    favicons = new FaviconCache(app.getPath('userData'), true);
    await favicons.load();
    blocker = await loadBlocker(RESOURCES_DIR);

    const guard = {
      ipcMain,
      isTrustedSender: (event: { readonly sender: unknown }) => windowFor(event.sender) !== null,
      onViolation: onIpcViolation,
    };

    registerWindowIpc({
      ...guard,
      getWindow: (sender) => windowFor(sender)?.window ?? null,
      getAppInfo,
      openPrivateWindow: () => {
        createWindow({ isPrivate: true });
      },
    });

    registerTabIpc({
      ...guard,
      getManager: (sender) => windowFor(sender)?.manager ?? null,
      getPanels: (sender) => windowFor(sender)?.panels ?? null,
      findPanel: (id) => settings?.current.webPanels.find((panel) => panel.id === id) ?? null,
      addPanel: (url, title) => {
        if (settings === null) return;
        const normalized = normalizeUrl(url);
        if (normalized === null) return;
        const existing = settings.current.webPanels;
        if (existing.some((panel) => panel.url === normalized) || existing.length >= 12) return;
        settings.update({
          webPanels: [
            ...existing,
            {
              id: randomUUID(),
              url: normalized,
              title: title.trim() === '' ? defaultTileTitle(normalized) : title,
              icon: favicons?.get(normalized) ?? null,
            },
          ],
        });
      },
      removePanel: (id) => {
        if (settings === null) return;
        settings.update({
          webPanels: settings.current.webPanels.filter((panel) => panel.id !== id),
        });
      },
      popupTabMenu: (manager, id, sender) => {
        const owner = windowFor(sender);
        if (owner !== null) popupTabMenu(owner.window, manager, id);
      },
    });

    registerSettingsIpc({
      ...guard,
      getStore: () => settings,
      getReport: (sender) => {
        const owner = windowFor(sender);
        return {
          adblockEnabled: blocker !== null && (settings?.current.blockAdsAndTrackers ?? false),
          settingsPath: settings?.path ?? '',
          blockedThisWindow: owner?.blockedCount ?? 0,
          privateSession: owner?.isPrivate ?? false,
          updateFeedUrl: UPDATE_FEED_URL,
          userAgent: USER_AGENT,
        };
      },
      cachedFavicon: (url) => favicons?.get(url) ?? null,
      vault: vault,
      fillLogin: async (sender, tabId) => {
        const owner = windowFor(sender);
        const tab = owner?.manager.find(tabId) ?? null;
        const contents = tab?.webContents ?? null;
        if (vault === null || contents === null) {
          return { ok: false, error: 'No page to fill.', filled: 0 };
        }
        if (!vault.unlocked) return { ok: false, error: 'Sign in first.', filled: 0 };

        let host: string;
        try {
          host = new URL(tab?.url ?? '').host;
        } catch {
          return { ok: false, error: 'This page has no address to match.', filled: 0 };
        }

        const entry = vault.findForHost(host);
        if (entry === null) {
          return { ok: false, error: `Nothing saved for ${host}.`, filled: 0 };
        }

        const password = vault.reveal(entry.id);
        // eslint-disable-next-line security/detect-possible-timing-attacks -- a null check on our own decrypt result, not a secret comparison
        if (password === null) return { ok: false, error: 'Could not read that entry.', filled: 0 };

        // The user pressed the key button, so this one overwrites whatever is
        // in the boxes and does not wait around for a form to appear.
        const filled = await fillLogin(contents, {
          username: entry.username,
          password,
          force: true,
          submit: false,
          waitMs: 0,
        });
        return filled === 0
          ? { ok: false, error: 'No login form found on this page.', filled: 0 }
          : { ok: true, error: null, filled };
      },
      resolveCapture: (sender, id, save) => {
        const owner = windowFor(sender);
        return owner === null
          ? { ok: false, error: 'That window has gone.' }
          : owner.resolveCapture(id, save);
      },
      models: {
        list: async () => {
          const store = modelStore;
          return Promise.all(
            MODEL_CATALOGUE.map(async (entry) => ({
              id: entry.id,
              label: entry.label,
              blurb: entry.blurb,
              parameters: entry.parameters,
              bytes: entry.bytes,
              needsBytes: entry.needsBytes,
              status: (await store?.status(entry.id)) ?? { state: 'absent' as const },
            })),
          );
        },
        download: (id) => {
          const store = modelStore;
          if (store === null)
            return Promise.resolve({ ok: false, error: 'Models are not ready yet.' });
          if (findModel(id) === null)
            return Promise.resolve({ ok: false, error: 'No such model.' });
          // Deliberately not awaited: a multi-gigabyte download is not a thing
          // to hold an IPC call open for. Progress arrives on its own channel.
          void store.download(id);
          return Promise.resolve({ ok: true, error: null });
        },
      },
      localRunner: {
        resolve: async (id) => (await modelStore?.pathIfReady(id)) ?? null,
        ask: async (modelPath, messages) => localModel.ask(modelPath, messages),
        describe: async (id) => {
          const entry = findModel(id);
          if (entry === null) return 'No model chosen. Pick one in Settings → Assistant.';

          const status = (await modelStore?.status(id)) ?? { state: 'absent' as const };
          switch (status.state) {
            case 'ready':
              return `${entry.label} runs inside Vela. Nothing leaves this machine — there is no server to leave to.`;
            case 'downloading': {
              const done = Math.round(
                (status.receivedBytes / Math.max(1, status.totalBytes)) * 100,
              );
              return `Downloading ${entry.label} — ${String(done)}%. This happens once.`;
            }
            case 'verifying':
              return `Checking ${entry.label} against its checksum.`;
            case 'failed':
              return `${entry.label} did not download: ${status.error}`;
            default:
              return `${entry.label} is not downloaded yet.`;
          }
        },
      },
      openOllamaDownload: (sender) => {
        // Opened in a Vela tab rather than handed to shell.openExternal: this
        // is a browser, and openExternal fails outright on a machine with no
        // working default-browser association — which is exactly the machine
        // someone installing a new browser is likely to have.
        //
        // Vela opens the page rather than running the installer: a browser
        // that silently executes downloaded binaries is not one to trust,
        // whatever the binary happens to be.
        const owner = windowFor(sender);
        owner?.manager.create({ url: 'https://ollama.com/download', active: true });

        return {
          opened: owner !== null,
          command:
            PLATFORM === 'win32'
              ? 'winget install Ollama.Ollama'
              : PLATFORM === 'darwin'
                ? 'brew install ollama'
                : 'curl -fsSL https://ollama.com/install.sh | sh',
        };
      },
      downloads: {
        list: (sender) => windowFor(sender)?.downloads.list ?? [],
        open: (sender, id) => windowFor(sender)?.downloads.open(id),
        showInFolder: (sender, id) => windowFor(sender)?.downloads.showInFolder(id),
        cancel: (sender, id) => windowFor(sender)?.downloads.cancel(id),
        clear: (sender) => windowFor(sender)?.downloads.clear(),
        togglePopup: (sender) => windowFor(sender)?.downloadPopup.toggle(),
        closePopup: (sender) => windowFor(sender)?.downloadPopup.hide(),
        setPopupHeight: (sender, height) => windowFor(sender)?.downloadPopup.setHeight(height),
      },
      history: {
        search: (query, limit) => history?.search(query, limit) ?? [],
        clear: () => history?.clear(),
      },
      updater: {
        get current(): UpdateState {
          return updater?.current ?? { status: 'idle', version: null, message: null };
        },
        check: () => updater?.check(),
        download: () => updater?.download(),
        install: () => updater?.install(),
      },
      clearData: async (sender) => {
        const owner = windowFor(sender);
        if (owner === null) return false;
        await clearBrowsingData(owner.session);
        return true;
      },
    });

    nativeTheme.on('updated', () => {
      for (const window of windows.values()) {
        window.window.setBackgroundColor(backgroundColor());
      }
    });

    createWindow({ isPrivate: false });

    startDevMetrics(IS_DEV, () =>
      [...windows.values()].reduce((total, window) => total + window.manager.count, 0),
    );

    // One check, a few seconds after start, so it never competes with the
    // first paint. Nothing is downloaded unless the user asks.
    setTimeout(() => {
      updater?.check();
    }, 5000).unref();

    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow({ isPrivate: false });
    });
  });

  app.on('window-all-closed', () => {
    if (PLATFORM !== 'darwin') {
      void clearOnExitIfRequested().finally(() => {
        app.quit();
      });
    }
  });
}
